version: 2.0
jobs:
  unit-test:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: "Static analysis"
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml ./src
      - run:
          name: "Unit tests suite"
          command: yarn test --ci --runInBand --coverage --reporters=default --reporters=jest-junit
          environment:
                  JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports

  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: "Build lib"
          command: yarn build

  examples-build:
    docker:
      - image: node:10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build Docs
          command: yarn build:dev
      - persist_to_workspace:
          root: dist/
          paths: examples

  examples-deploy:
    docker:
      - image: node:10
    steps:
      - checkout
      # Download and cache dependencies
      - add_ssh_keys:
          fingerprints:
            - "3f:14:23:67:fd:40:0a:6f:1b:47:17:ba:b8:e8:ff:e5"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --pure-lockfile
      - attach_workspace:
          at: dist/
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "ci-build@circleci.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: yarn gh-pages -d dist/examples --message "[Storybook] Deploy [skip ci]" 

workflows:
  version: 2
  master:
    jobs:
      - unit-test:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - unit-test
          filters:
            branches:
              only:
                - master
      - examples-build:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - examples-deploy:
          requires:
            - examples-build
          filters:
            branches:
              only:
                - master
