version: 2.0
jobs:
  unit-test:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: "Static analysis"
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml ./src
      - run:
          name: "Unit tests suite"
          command: yarn test --ci --runInBand --coverage --reporters=default --reporters=jest-junit
          environment:
                  JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports

  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: "Build lib"
          command: yarn build

  examples-build:
    docker:
      - image: node:10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build Docs
          command: yarn build:dev
      - persist_to_workspace:
          root: docs/
          paths: examples
      - store_artifacts:
          path: docs

  examples-deploy:
    docker:
      - image: node:10
    steps:
      - checkout
      # Download and cache dependencies
      - add_ssh_keys:
          fingerprints:
            - "d8:92:3b:19:04:03:a9:29:cb:bc:72:c6:d7:2e:0b:cc"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --pure-lockfile
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "ci-build@circleci.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages -d docs/examples --message "[Storybook] Deploy [skip ci]" 

workflows:
  version: 2
  master:
    filters:
      branches:
        only:
          - master
    jobs:
      - unit-test
      - build:
          requires:
            - unit-test
      - examples-build:
          requires:
            - build
      - examples-deploy:
          requires:
            - examples-build
